(async()=>{
const V6=window.MENAGERIE_V6;window.V6=V6;
function replaceOrThrow(src,a,b,label){if(!src.includes(a))throw new Error('V6 no pudo aplicar: '+label);return src.replace(a,b)}
window.__MENAGERIE_V6_PATCH__=function(src){
 src=replaceOrThrow(src,"['ashwing','iron_cub','red_hare','moss_boar','hollow_crow','rune_crab','marrow_wolf','lantern_fox'].forEach(id=>run.deck.push(cardFrom(id)))","V6.starter.forEach(id=>run.deck.push(cardFrom(id)))",'mazo inicial de cuatro');
 src=replaceOrThrow(src,"function nodeType(r){if(r===1)return'hunt';if(r===2)return rand(['hunt','hunt','camp','archive','graft']);if(r===3)return rand(['hunt','alpha','camp','archive','graft','merchant','reliquary']);return rand(['hunt','alpha','merchant','reliquary','altar','omen','camp'])}","function nodeType(r){if(r===1)return'hunt';if(r===2)return rand(['camp','archive','graft','omen','archive']);if(r===3)return rand(['hunt','hunt','alpha']);return rand(['merchant','reliquary','altar','omen','camp','graft','archive','alpha'])}",'dramaturgia del mapa');
 src=replaceOrThrow(src,"pool=boss?boss.pool:D.beasts.map(x=>x.id)","pool=boss?boss.pool:D.beasts.filter(x=>(x.unlockTier||1)<=run.act).map(x=>x.id)",'desbloqueo rival');
 src=replaceOrThrow(src,"while(pool.length<3)pool.push(rand(D.beasts).id)","{let unlocked=D.beasts.filter(x=>(x.unlockTier||1)<=run.act);while(pool.length<3)pool.push(rand(unlocked).id)}",'capturas desbloqueadas');
 src=replaceOrThrow(src,"let offers=shuffle(D.beasts.slice()).slice(0,3)","let offers=shuffle(D.beasts.filter(x=>(x.unlockTier||1)<=run.act)).slice(0,3)",'taquilla desbloqueada');
 src=replaceOrThrow(src,"focus:3,echoes:","focus:V6.focusBase,echoes:",'foco inicial');
 src=replaceOrThrow(src,"battle.focus+=gain;battle.echoes++;","battle.focus=Math.min(V6.focusCap,battle.focus+gain);battle.echoes=Math.min(V6.echoCap,battle.echoes+1);",'retirada con límites');
 src=src.replace(/battle\.echoes\+\+/g,"battle.echoes=Math.min(V6.echoCap,battle.echoes+1)");
 src=src.replace(/battle\.focus\+\+/g,"battle.focus=Math.min(V6.focusCap,battle.focus+1)");
 src=replaceOrThrow(src,"battle.focus=3+(battle.encore||0)","battle.focus=Math.min(V6.focusCap,V6.focusBase+(battle.encore||0))",'renovación de foco');
 src=replaceOrThrow(src,"$('#focusTxt').textContent=battle.focus;$('#echoTxt').textContent=battle.echoes;","$('#focusTxt').textContent=battle.focus+'/'+V6.focusCap;$('#echoTxt').textContent=battle.echoes+'/'+V6.echoCap;",'topes visibles');
 src=src.replace("count=boss?8:type==='alpha'?7:6+Math.min(2,Math.floor(run.depth/7))","count=boss?8:type==='alpha'?7:(run.act===1?5:6+Math.min(2,Math.floor(run.depth/7)))");
 src=src.replace("Math.random()<(boss?.82:type==='alpha'?.74:.64)","Math.random()<(boss?.82:type==='alpha'?.72:(run.act===1?.54:.64))");
 src=replaceOrThrow(src,"w.className='map-node '+(n.type==='boss'?'boss ':'')","w.className='map-node type-'+n.type+' '+(n.type==='boss'?'boss ':'')",'tipos visuales del mapa');
 src=replaceOrThrow(src,"function onLane(i){if(busy)return;","function onLane(i){if(busy)return;if(battle.boss?.id==='bell_man'&&battle.blockedLane===i&&selected>=0&&!retireMode){toast('BASTIDORES CERRADOS · este carril vuelve a abrirse al cambiar la tramoya.');return}",'carril bloqueado');
 src=replaceOrThrow(src,"if(retireMode&&battle.player[i])l.classList.add('retire-ready');else if(selected>=0&&!battle.player[i]&&canPay(battle.hand[selected]))l.classList.add('ready');","if(battle.boss?.id==='bell_man'&&battle.blockedLane===i)l.classList.add('blocked-lane');if(retireMode&&battle.player[i])l.classList.add('retire-ready');else if(selected>=0&&!battle.player[i]&&canPay(battle.hand[selected])&&!(battle.boss?.id==='bell_man'&&battle.blockedLane===i))l.classList.add('ready');",'carril bloqueado visible');
 src=replaceOrThrow(src,"<div class=\"card-crest\">${c.tribe||'Figurante'}</div>","<div class=\"unit-cost ${c.costType}\">${c.cost}${c.costType==='echo'?' E':' F'}</div><div class=\"card-crest\">${c.tribe||'Figurante'}</div>",'coste en mesa');
 src=src.replace(/function bossHint\(\)\{[\s\S]*?\}function renderBattle/,`function bossHint(){let b=battle?.boss;if(!b)return'';if(b.id==='taxidermist')return battle.turn%2===0?'PRÓXIMO: el Regidor girará tu reparto un carril.':'Cada segundo turno cambia tus posiciones.';if(b.id==='silk_mother')return battle.turn%2===0?'PRÓXIMO: proyectará un Doblete de Cera.':'Duplica periódicamente a su intérprete más fuerte.';if(b.id==='bell_man')return'BASTIDORES CERRADOS: carril '+((battle.blockedLane??0)+1)+'.';if(b.id==='hungry_one')return'El Corifeo copiará el mayor ATQ visible de tu reparto.';if(b.id==='mirror_choir')return'Cada hueco de tu reparto cede 1 Presión al final del turno.';if(b.id==='pale_director')return battle.turn>=4?'ACTO FINAL · su compañía gana fuerza cada cuarto turno.':'Tu Encore desaparece ante su Cadenza.';return b.rule}function renderBattle`);
 src=replaceOrThrow(src,"if(chip){if(battle.boss){chip.classList.remove('hidden');chip.innerHTML='<b>'+battle.boss.name+'</b><span>'+bossHint()+'</span>'}else chip.classList.add('hidden')}","if(chip){if(battle.boss){chip.classList.remove('hidden');chip.innerHTML='<b>'+battle.boss.name+'</b><span>'+bossHint()+'</span>'}else chip.classList.add('hidden')}let bp=$('#bossPortrait');if(bp){if(battle.boss){bp.classList.remove('hidden');bp.innerHTML='<img src=\"'+A.bossArt(battle.boss.id)+'\"><div><small>MAESTRO DE ACTO</small><b>'+battle.boss.name+'</b></div>'}else bp.classList.add('hidden')}",'retrato de jefe');
 src=src.replace(/async function bossRule\(\)\{[\s\S]*?\}function checkEnd/,`async function bossRule(){let b=battle.boss;if(!b)return;if(b.id==='taxidermist'&&battle.turn%2===0){battle.player=[battle.player[2],battle.player[0],battle.player[1]];toast('EL REGIDOR · cambia las marcas de posición.');sfx('chime');await wait(160)}if(b.id==='silk_mother'&&battle.turn%2===0){let open=[0,1,2].filter(i=>!battle.enemy[i]&&!battle.queue[i]),src=battle.enemy.filter(Boolean).sort((a,b)=>displayAtk(b)-displayAtk(a))[0];if(open.length&&src){let c=clone(src);c.uid=uid();c.name='Doblete de Cera';c.atk=Math.max(1,Math.ceil(displayAtk(src)/2));c.maxHp=c.hp=Math.max(2,Math.ceil(src.maxHp/2));c.sigils=[];battle.queue[rand(open)]=c;toast('LA PRIMA DONNA · proyecta un doble de cera.')}}if(b.id==='bell_man'){battle.blockedLane=((battle.blockedLane??-1)+1)%3;toast('TRAMOYA · se cierra el carril '+(battle.blockedLane+1)+'.')}if(b.id==='hungry_one'){let max=Math.max(0,...battle.player.filter(Boolean).map(displayAtk)),e=battle.enemy.filter(Boolean).sort((a,b)=>displayAtk(b)-displayAtk(a))[0];if(e&&max>displayAtk(e)){e.atk=max;toast('EL CORIFEO · '+e.name+' imita ATQ '+max+'.')}}if(b.id==='mirror_choir'){let empty=battle.player.filter(x=>!x).length;if(empty){shiftPressure(-Math.min(2,empty));toast('EL PÚBLICO VACÍO · el silencio ocupa '+empty+' carril'+(empty>1?'es':'')+'.')}}if(b.id==='pale_director'&&battle.turn%4===0){battle.enemy.filter(Boolean).forEach(c=>{c.atk++;c.maxHp++;c.hp++});shiftPressure(-1);toast('ACTO FINAL · la compañía del Director se eleva +1/+1.');sfx('boss');await wait(180)}}function checkEnd`);
 src=replaceOrThrow(src,"bossMemory:new Set,lastEchoes:0,bossLane:0,bossMirrorLane:0}","bossMemory:new Set,lastEchoes:0,bossLane:0,bossMirrorLane:0,blockedLane:0}",'estado jefe v6');
 src=src.replace(/function showAwaken\(c,lane\)\{[\s\S]*?\}function refillQueue/,`function showAwaken(c,lane){let o=$('#awakenOverlay'),newSig=c.wake%2===0&&c.sigils.length?D.sigils[c.sigils[c.sigils.length-1]]?.name:null;o.innerHTML='<div class="awaken-stage"><div class="awaken-spot"></div><div class="awaken-curtain left"></div><div class="awaken-curtain right"></div><div class="awaken-sheet"><div class="eyebrow">DESPERTAR · ACTO '+roman(c.wake)+'</div><div class="awaken-art"><img src="'+art(c)+'"></div><h2>'+c.name+'</h2><p>La máscara anterior se agrieta. El público reconoce una presencia distinta.</p><div class="awaken-stats"><span><b>'+displayAtk(c)+'</b> ATQ</span><i>◆</i><span><b>'+c.maxHp+'</b> VIDA</span></div>'+(newSig?'<div class="awaken-sigil">NUEVO GESTO · '+newSig+'</div>':'<div class="awaken-sigil">EL PAPEL SE PROFUNDIZA</div>')+'<small>TOCA PARA VOLVER A LA ESCENA</small></div></div>';o.classList.remove('hidden');void o.offsetWidth;o.classList.add('show');let close=()=>{o.classList.add('closing');setTimeout(()=>{o.classList.add('hidden');o.classList.remove('show','closing')},420)};o.onclick=close;setTimeout(()=>{if(!o.classList.contains('hidden'))close()},3200);let el=$('#playerSide').children[lane]?.querySelector('.unit-card');if(el)el.classList.add('awakened');sfx('chime')}function refillQueue`);
 const omenRe=/function omenEvent\(id\)\{[\s\S]*?\}function reliquaryEvent/;
 if(omenRe.test(src))src=src.replace(omenRe,`function omenEvent(id){let r=Math.random()*5|0;if(r===0){let c=rand(run.deck);modal('PRESAGIO · DOBLE PAPEL',\`<h2>\${c.name} figura dos veces en el programa</h2><p>Puede ganar 2 memorias ahora, pero otra presencia recibirá una Herida.</p><button id="omenYes" style="width:100%">ACEPTAR</button><button id="omenNo" style="width:100%;margin-top:8px">IGNORAR</button>\`);$('#omenYes').onclick=()=>{c.kills+=2;let o=rand(run.deck.filter(x=>x.uid!==c.uid));if(o)o.scar++;closeModal();clearNode(id)};$('#omenNo').onclick=()=>{closeModal();clearNode(id)}}else if(r===1){modal('PRESAGIO · BUTACA IV',\`<h2>Una butaca lleva tu nombre</h2><p>Recoge 5 Fragmentos, pero la siguiente Escena comenzará con 1 Presión menos.</p><button id="omenYes" style="width:100%">SENTARSE</button><button id="omenNo" style="width:100%;margin-top:8px">PASAR DE LARGO</button>\`);$('#omenYes').onclick=()=>{run.fragments+=5;run.cadencePact=true;closeModal();clearNode(id)};$('#omenNo').onclick=()=>{closeModal();clearNode(id)}}else if(r===2){let a=shuffle(run.deck.slice()).slice(0,2);if(a.length<2)return archiveEvent(id);modal('PRESAGIO · ESPEJO DE ENSAYO',\`<h2>Dos papeles han intercambiado sus reflejos</h2><p>\${a[0].name} y \${a[1].name} pueden intercambiar su Ataque base.</p><button id="omenYes" style="width:100%">INTERCAMBIAR</button><button id="omenNo" style="width:100%;margin-top:8px">ROMPER EL ESPEJO</button>\`);$('#omenYes').onclick=()=>{[a[0].atk,a[1].atk]=[a[1].atk,a[0].atk];closeModal();clearNode(id)};$('#omenNo').onclick=()=>{run.fragments+=2;closeModal();clearNode(id)}}else if(r===3){let pool=D.beasts.filter(x=>(x.unlockTier||1)<=run.act&&!run.deck.some(c=>c.species===x.id));let s=pool.length?rand(pool):null;if(!s)return archiveEvent(id);modal('PRESAGIO · SUPLENTE',\`<h2>\${s.name} espera detrás del telón</h2><p>Puede unirse sin coste, pero una presencia aleatoria del reparto recibirá una Herida.</p><button id="omenYes" style="width:100%">DARLE ENTRADA</button><button id="omenNo" style="width:100%;margin-top:8px">RECHAZAR</button>\`);$('#omenYes').onclick=()=>{run.deck.push(cardFrom(s.id));rand(run.deck).scar++;closeModal();clearNode(id)};$('#omenNo').onclick=()=>{run.fragments+=2;closeModal();clearNode(id)}}else{let c=rand(run.deck);modal('PRESAGIO · CRÍTICA SIN FIRMA',\`<h2>Una reseña describe a \${c.name} de dos maneras incompatibles</h2><div id="eventGrid" class="reward-grid"></div>\`);let g=$('#eventGrid'),ops=[['Más feroz','+1 ATQ · −1 VIDA máxima',()=>{c.atk++;c.maxHp=Math.max(1,c.maxHp-1);c.hp=Math.min(c.hp,c.maxHp)}],['Más inolvidable','+2 VIDA máxima · −1 ATQ',()=>{c.maxHp+=2;c.hp+=2;c.atk=Math.max(0,c.atk-1)}]];for(let[n,t,f]of ops){let d=document.createElement('div');d.className='choice';d.innerHTML=\`<h3>\${n}</h3><p>\${t}</p>\`;d.onclick=()=>{f();closeModal();clearNode(id)};g.appendChild(d)}}}function reliquaryEvent`);
 src=src.replace("<div class=\"trait\"><b>10 · Maestros de Acto</b><span>Cada jefe cambia una regla y su próxima amenaza se muestra sobre la escena.</span></div>","<div class=\"trait\"><b>10 · Maestros de Acto</b><span>Cada jefe cambia una regla y su próxima amenaza se muestra sobre la escena.</span></div><div class=\"trait\"><b>11 · Repertorio</b><span>La run comienza con cuatro presencias sencillas. Nuevos intérpretes se desbloquean Acto a Acto.</span></div><div class=\"trait\"><b>12 · Capacidad</b><span>Foco máximo 7 · Eco máximo 9. Las cartas tardías usan esa capacidad para justificar su poder.</span></div>");
 return src;
};
 const r=await fetch('boot-v5.js?rev=6.0.0',{cache:'no-store'});if(!r.ok)throw new Error('No se pudo cargar la base V5: '+r.status);let loader=await r.text();
 const needle="(0,eval)(src+'\\n//# sourceURL=menagerie-v5-runtime.js');";
 if(!loader.includes(needle))throw new Error('V6 no pudo enlazar con el runtime V5');
 loader=loader.replace(needle,"src=window.__MENAGERIE_V6_PATCH__(src);(0,eval)(src+'\\n//# sourceURL=menagerie-v6-runtime.js');");
 (0,eval)(loader+'\n//# sourceURL=menagerie-v6-loader.js');
})().catch(err=>{console.error(err);document.body.insertAdjacentHTML('beforeend',`<pre style="position:fixed;inset:12px;z-index:9999;overflow:auto;background:#130b0c;color:#ffd8d8;border:1px solid #633;padding:16px;white-space:pre-wrap;font:13px/1.5 monospace">THE LAST MENAGERIE · V6 no pudo iniciar.\n\n${err.message}</pre>`)});
